import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";


const ProfilePage: NextPage = () => {
  // Start fetching posts ASAP (use cached data elsewhere)
  api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Plant Journal App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-center">
        <div>
          Profile View
        </div>
      </main>
    </>
  );
};

export default ProfilePage;
