import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import { PageLayout } from "@/components/layout";


const SinglePostPage: NextPage = () => {
  // Start fetching posts ASAP (use cached data elsewhere)
  api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <PageLayout>
        <div>
          Single Post Page
        </div>
      </PageLayout>
    </>
  );
};

export default SinglePostPage;
